on: push
name: ğŸš€ Deploy Next.js app (SSR)
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Checkout code
        uses: actions/checkout@v4

      - name: ğŸŸ¢ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: ğŸ“¦ Install dependencies
        run: npm install --legacy-peer-deps --production=false

      - name: ğŸ—ï¸ Build Next.js
        run: npm run build

      - name: ğŸ“‚ Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ftp.verdsoft.co.zw
          username: bms@bms.verdsoft.co.zw
          password: ${{ secrets.ftp_password }}
          local-dir: ./
          server-dir: /home/verdsoft/bms.verdsoft.co.zw/
